# -*- coding: utf-8 -*-
"""sugarcane_xai_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXAzgdPHnCWXWUUiq2OIRD6r08hPj5Q7

# Explainable AI for Deep Learning-Based Plant Disease Detection
Objective 1 (train ConvNeXt-Tiny / EfficientNetV2-S / MobileNetV4) and Objective 2 (Grad-CAM++ / Layer-CAM / Eigen-CAM visual explanations) done. Objectives 3 and 4 (Deletion/Insertion AUC, Pointing Game, quantitative heatmap comparison) are yet to implemented.
"""

# CELL 1 — Install dependencies
!pip install -q -U "timm>=1.0.9" grad-cam albumentations opencv-python-headless scikit-learn pandas matplotlib tqdm

# CELL 2 — Imports and configuration
import os, io, re, sys, json, copy, time, shutil, random, hashlib, logging, zipfile, inspect, warnings
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, get_worker_info
import timm
import albumentations as A
from albumentations.pytorch import ToTensorV2
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import (accuracy_score, precision_recall_fscore_support,
                             confusion_matrix, classification_report)

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s", force=True)
logger = logging.getLogger("sugarcane_xai")


CONFIG = {
    # ---- paths ----
    "ZIP_PATH": "/content/Sugarcane Plant Disease Dataset of Assam.zip",
    "OUTPUT_DIR": "/content/sugarcane_xai_outputs",

    # ---- data ----
    "IMAGE_SIZE": 224,
    "VAL_FRAC": 0.15,
    "TEST_FRAC": 0.15,
    "GROUP_BY_FILENAME": True,      # group augmented copies (e.g. img_aug1) so they never straddle splits
    "SEED": 42,

    # ---- training ----
    "MODELS": ["convnext_tiny", "efficientnetv2_s", "mobilenetv4"],
    "MOBILENETV4_VARIANT": "mobilenetv4_conv_medium",   # any name from timm.list_models("mobilenetv4*")
    "PRETRAINED": True,
    "BATCH_SIZE": 32,
    "NUM_EPOCHS": 20,
    "LEARNING_RATE": 1e-4,
    "WEIGHT_DECAY": 1e-2,
    "NUM_WORKERS": 2,
    "USE_AMP": True,                # only effective on CUDA
    "EARLY_STOP_PATIENCE": 5,
    "USE_CLASS_WEIGHTS": True,      # inverse-frequency weights (helps if classes are imbalanced)
    "USE_FOCAL_LOSS": False,        # optional; default is Cross Entropy
    "FOCAL_GAMMA": 2.0,
    "USE_5_FOLD_CV": False,         # True => stratified group 5-fold CV on the train+val pool
    "N_FOLDS": 5,
    "DETERMINISTIC": True,

    # ---- augmentation (mild, to preserve disease symptoms) ----
    "AUG_ROTATE_DEG": 20,
    "AUG_SCALE": (0.9, 1.1),
    "AUG_COLOR_JITTER": 0.2,        # brightness/contrast/saturation

    # ---- XAI ----
    "XAI_METHODS": ["gradcam++", "layercam", "eigencam"],
    "NUM_XAI_SAMPLES": 20,
    "DEMO_IMAGE_PATH": None,        # None => first test image
}

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]
IMG_EXT = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}

OUT = Path(CONFIG["OUTPUT_DIR"])
DIRS = {k: OUT / k for k in ["extracted", "checkpoints", "plots", "results", "xai"]}

# CELL 3 — Reproducibility and device setup
def set_seed(seed: int, deterministic: bool = True) -> None:
    """Seed Python, NumPy, PyTorch (CPU+CUDA).

    Limitation: even with fixed seeds, some CUDA kernels (atomic adds in certain backward passes,
    AMP fp16 accumulation, non-deterministic cuDNN algorithms) can produce tiny run-to-run differences.
    We set cudnn.deterministic=True and benchmark=False, but full bitwise reproducibility is not guaranteed
    across GPU types, driver/library versions, or DataLoader worker counts.
    """
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = deterministic
    torch.backends.cudnn.benchmark = not deterministic


def setup_device() -> torch.device:
    print(f"PyTorch version : {torch.__version__}")
    print(f"timm version    : {timm.__version__}")
    print(f"CUDA available  : {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"GPU name        : {torch.cuda.get_device_name(0)}")
    else:
        print("WARNING: CUDA unavailable -> running on CPU (fine for testing, very slow for training).")
    dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Selected device : {dev}")
    return dev


set_seed(CONFIG["SEED"], CONFIG["DETERMINISTIC"])
device = setup_device()
USE_AMP = bool(CONFIG["USE_AMP"] and device.type == "cuda")
print(f"Mixed precision : {USE_AMP}")
for d in DIRS.values():
    d.mkdir(parents=True, exist_ok=True)

# CELL 4 — ZIP extraction and dataset discovery
GENERIC_DIR_NAMES = {"images", "image", "imgs", "img", "photos", "data", "dataset", "jpg", "jpeg", "png"}
SPLIT_DIR_NAMES = {"train", "training", "val", "valid", "validation", "test", "testing"}


def extract_dataset(zip_path: Union[str, Path], extract_dir: Union[str, Path], force: bool = False) -> Path:
    """Safely extract a ZIP (blocks path traversal). Re-uses a previous extraction of the same ZIP."""
    zip_path, extract_dir = Path(zip_path), Path(extract_dir)
    print(f"ZIP path            : {zip_path}")
    print(f"Extraction directory: {extract_dir}")
    if not zip_path.exists():
        raise FileNotFoundError(f"ZIP file not found: {zip_path}. Upload it to Colab and update CONFIG['ZIP_PATH'].")
    if not zipfile.is_zipfile(zip_path):
        raise zipfile.BadZipFile(f"Not a valid ZIP file: {zip_path}")
    marker = extract_dir / ".extraction_complete"
    signature = str(zip_path.stat().st_size)
    if marker.exists() and marker.read_text() == signature and not force:
        print("Existing extraction of this ZIP found -> re-using it.")
        return extract_dir
    if extract_dir.exists():
        shutil.rmtree(extract_dir)
    extract_dir.mkdir(parents=True)
    root = extract_dir.resolve()
    with zipfile.ZipFile(zip_path) as zf:
        bad = zf.testzip()
        if bad is not None:
            raise zipfile.BadZipFile(f"Corrupted member inside ZIP: {bad}")
        for member in tqdm(zf.infolist(), desc="Extracting"):
            target = (extract_dir / member.filename).resolve()
            if target != root and root not in target.parents:
                raise ValueError(f"Unsafe path in ZIP (path traversal): {member.filename}")
            zf.extract(member, extract_dir)
    marker.write_text(signature)
    return extract_dir


def discover_dataset(root: Union[str, Path]) -> pd.DataFrame:
    """Recursively locate images and infer class labels from folder structure.

    Rule: every directory that directly contains images is an 'image directory'. Its class is the directory
    name, unless that name is generic ('images', 'data', ...) or a split name ('train', 'val', 'test'), in which
    case we walk up to the parent. Same class name found under several split folders is merged (and reported).
    """
    root = Path(root)
    image_dirs: Dict[Path, List[str]] = {}
    ext_counter: Dict[str, int] = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d != "__MACOSX"]
        imgs = [f for f in filenames if not f.startswith(".") and Path(f).suffix.lower() in IMG_EXT]
        for f in imgs:
            e = Path(f).suffix.lower()
            ext_counter[e] = ext_counter.get(e, 0) + 1
        if imgs:
            image_dirs[Path(dirpath)] = imgs
    if not image_dirs:
        raise RuntimeError(f"No image files ({sorted(IMG_EXT)}) found under {root}.")

    records, depths, split_dirs_seen = [], set(), set()
    for d, files in image_dirs.items():
        label_dir = d
        while label_dir != root and label_dir.name.lower() in (GENERIC_DIR_NAMES | SPLIT_DIR_NAMES):
            label_dir = label_dir.parent
        if label_dir == root:
            raise RuntimeError(
                f"Images found in '{d}' but no class folder could be inferred (images sit directly in the "
                f"dataset root or only in generic/split-named folders). Expected class_name/image.jpg layout.")
        rel_parts = [p.lower() for p in d.relative_to(root).parts]
        src_split = next((p for p in rel_parts if p in SPLIT_DIR_NAMES), "")
        if src_split:
            split_dirs_seen.add(src_split)
        depths.add(len(label_dir.relative_to(root).parts))
        for f in files:
            records.append({"path": str(d / f), "class_name": label_dir.name,
                            "source_split": src_split, "source_dir": str(d.relative_to(root))})
    df = pd.DataFrame(records).sort_values("path").reset_index(drop=True)

    n_cls = df["class_name"].nunique()
    if n_cls < 2:
        raise RuntimeError(f"Only {n_cls} class folder detected ({df['class_name'].unique()}); need >= 2.")

    print("\n=== DATASET STRUCTURE ===")
    print(f"Dataset root           : {root}")
    print(f"Class-folder depth(s)  : {sorted(depths)} level(s) below the root")
    print(f"Pre-existing split dirs: {sorted(split_dirs_seen) or 'none'}"
          + ("  -> images will be POOLED and re-split by this pipeline." if split_dirs_seen else ""))
    print(f"Image extensions found : {ext_counter}")
    print(f"Discovered class folders ({n_cls}):")
    counts = df["class_name"].value_counts().sort_index()
    for name, c in counts.items():
        print(f"   {name:<40s} {c:>6d} images")
    print(f"Total images           : {len(df)}")
    if n_cls != 9:
        print(f"NOTE: synopsis describes 9 classes (8 diseases + healthy) but {n_cls} were discovered. "
              f"Check the class list above before trusting results.")
    return df


extract_dir = extract_dataset(CONFIG["ZIP_PATH"], DIRS["extracted"])
DISCOVERED_DF = discover_dataset(extract_dir)

# CELL 5 — Dataset validation
def validate_images(df: pd.DataFrame) -> Tuple[pd.DataFrame, List[Tuple[str, str]]]:
    """Decode every image, record size + content hash, drop unreadable files (and report them)."""
    good, bad = [], []
    for row in tqdm(df.itertuples(index=False), total=len(df), desc="Validating images"):
        try:
            data = Path(row.path).read_bytes()
            md5 = hashlib.md5(data).hexdigest()
            with Image.open(io.BytesIO(data)) as im:
                im.verify()
            with Image.open(io.BytesIO(data)) as im:
                im = im.convert("RGB")
                w, h = im.size
            good.append({**row._asdict(), "md5": md5, "width": w, "height": h})
        except Exception as e:  # noqa: BLE001
            bad.append((row.path, f"{type(e).__name__}: {e}"))
    if not good:
        raise RuntimeError("No readable images remain after validation.")
    out = pd.DataFrame(good)
    print(f"\nReadable images: {len(out)} | corrupted/unreadable: {len(bad)}")
    for p, err in bad[:20]:
        print(f"   BAD: {p} -> {err}")
    if len(bad) > 20:
        print(f"   ... and {len(bad) - 20} more")
    print(f"Resolution range: width {out.width.min()}-{out.width.max()}, height {out.height.min()}-{out.height.max()}")
    cnt = out["class_name"].value_counts()
    ratio = cnt.max() / cnt.min()
    print(f"Class imbalance ratio (max/min): {ratio:.2f}" + ("  -> imbalance present (class weights recommended)" if ratio > 1.5 else ""))
    return out, bad


VALID_DF, CORRUPTED = validate_images(DISCOVERED_DF)
class_names: List[str] = sorted(VALID_DF["class_name"].unique())
class_to_idx: Dict[str, int] = {c: i for i, c in enumerate(class_names)}
num_classes = len(class_names)
VALID_DF["label"] = VALID_DF["class_name"].map(class_to_idx)
print(f"\nnum_classes = {num_classes}\nclass_to_idx = {class_to_idx}")

# CELL 6 — Train/validation/test split
_AUG_TOKEN = re.compile(
    r"([_\-\s]?(aug(mented)?|copy|rot(ated)?|flip(ped)?|mirror)[_\-]?\d*)|(\(\d+\))|([_\-]\d+$)",
    re.I,
)


def assign_groups(df: pd.DataFrame, group_by_filename: bool = True) -> pd.DataFrame:
    """Assign leakage-groups: byte-identical files (md5) and, optionally, filename variants
    (same class + same stem after removing augmentation tokens like _aug1, _copy, (2)) share a group id."""
    parent = list(range(len(df)))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[rj] = ri

    keys = [df["md5"].tolist()]
    if group_by_filename:
        keys.append(
            [
                f"{c}|{_AUG_TOKEN.sub('', Path(p).stem).lower()}"
                for c, p in zip(df.class_name, df.path)
            ]
        )

    for key_list in keys:
        first: Dict[str, int] = {}
        for i, k in enumerate(key_list):
            if k in first:
                union(first[k], i)
            else:
                first[k] = i

    df = df.copy()
    df["group_id"] = [find(i) for i in range(len(df))]
    sizes = df["group_id"].map(df["group_id"].value_counts())
    n_multi = df.loc[sizes > 1, "group_id"].nunique()
    print(
        f"Leakage groups: {df.group_id.nunique()} groups; {n_multi} contain >1 image ({int((sizes > 1).sum())} images)."
    )
    if n_multi == 0:
        print(
            "  No duplicate/variant grouping information found -> near-duplicate leakage cannot be excluded "
            "if the dataset contains pre-augmented copies with unrelated filenames."
        )
    return df


def _group_holdout(
    df: pd.DataFrame, frac: float, seed: int
) -> Tuple[np.ndarray, np.ndarray]:
    """Stratified, group-aware holdout of ~frac of df. Returns (rest_idx, holdout_idx) as positional indices."""
    n_splits = max(2, int(round(1.0 / frac)))
    sgkf = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    rest, hold = next(sgkf.split(df, df["label"], df["group_id"]))
    return rest, hold


def create_splits(
    df: pd.DataFrame,
    val_frac: float,
    test_frac: float,
    seed: int,
    group_by_filename: bool = True,
) -> pd.DataFrame:
    """Stratified + group-aware train/val/test split with leakage checks. Adds a 'split' column."""
    if df["class_name"].value_counts().min() < 10:
        warnings.warn("A class has <10 images; stratified splits will be very small.")

    df = assign_groups(df, group_by_filename).reset_index(drop=True)

    rest_idx, test_idx = _group_holdout(df, test_frac, seed)
    rest = df.iloc[rest_idx].reset_index(drop=True)

    tr_idx, va_idx = _group_holdout(rest, val_frac / (1.0 - test_frac), seed)

    df["split"] = ""
    df.loc[df.index[test_idx], "split"] = "test"

    rest_paths_val = set(rest.iloc[va_idx]["path"])
    rest_paths_tr = set(rest.iloc[tr_idx]["path"])

    df.loc[df["path"].isin(rest_paths_val), "split"] = "val"
    df.loc[df["path"].isin(rest_paths_tr), "split"] = "train"

    # Print summary & verify no group leakage across splits
    counts = pd.crosstab(df["class_name"], df["split"])
    print("\n=== SPLIT SUMMARY ===")
    print(counts)
    print("\nSplit proportions:")
    print((df["split"].value_counts(normalize=True) * 100).round(2).to_string())

    # Verify zero leakage across groups
    train_groups = set(df[df["split"] == "train"]["group_id"])
    val_groups = set(df[df["split"] == "val"]["group_id"])
    test_groups = set(df[df["split"] == "test"]["group_id"])

    assert len(train_groups & val_groups) == 0, "Leakage detected between train and val!"
    assert len(train_groups & test_groups) == 0, "Leakage detected between train and test!"
    assert len(val_groups & test_groups) == 0, "Leakage detected between val and test!"
    print("\n✓ No group leakage detected between train, val, and test splits.")

    return df


SPLIT_DF = create_splits(
    VALID_DF,
    val_frac=CONFIG["VAL_FRAC"],
    test_frac=CONFIG["TEST_FRAC"],
    seed=CONFIG["SEED"],
    group_by_filename=CONFIG["GROUP_BY_FILENAME"],
)

# CELL 7 — Dataset and augmentation pipeline
def build_transforms(image_size: int, train: bool, cfg: dict = CONFIG) -> A.Compose:
    """Train: mild geometric + colour augmentation. Val/test/inference: deterministic resize + normalize only."""
    ops: list = [A.Resize(height=image_size, width=image_size)]
    if train:
        j = cfg["AUG_COLOR_JITTER"]
        ops += [
            A.HorizontalFlip(p=0.5),
            A.Affine(scale=tuple(cfg["AUG_SCALE"]), rotate=(-cfg["AUG_ROTATE_DEG"], cfg["AUG_ROTATE_DEG"]), p=0.5),
            A.ColorJitter(brightness=j, contrast=j, saturation=j, hue=0.02, p=0.5),
        ]
    ops += [A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD), ToTensorV2()]
    return A.Compose(ops)


class PlantDiseaseDataset(Dataset):
    """Reads RGB images from a DataFrame with columns 'path' and 'label'."""

    def __init__(self, df: pd.DataFrame, transform: A.Compose):
        self.paths = df["path"].tolist()
        self.labels = df["label"].astype(int).tolist()
        self.transform = transform

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, i: int):
        img = np.array(Image.open(self.paths[i]).convert("RGB"))
        x = self.transform(image=img)["image"]
        return x, self.labels[i]


def _worker_init_fn(worker_id: int) -> None:
    seed = torch.initial_seed() % 2**32
    random.seed(seed)
    np.random.seed(seed)
    info = get_worker_info()
    tf = getattr(info.dataset, "transform", None) if info else None
    if tf is not None and hasattr(tf, "set_random_seed"):   # albumentations >= 2.x
        try:
            tf.set_random_seed(seed)
        except Exception:  # noqa: BLE001
            pass


def make_loader(df: pd.DataFrame, train: bool, cfg: dict = CONFIG) -> DataLoader:
    ds = PlantDiseaseDataset(df, build_transforms(cfg["IMAGE_SIZE"], train, cfg))
    g = torch.Generator().manual_seed(cfg["SEED"])
    nw = cfg["NUM_WORKERS"]
    return DataLoader(ds, batch_size=cfg["BATCH_SIZE"], shuffle=train, drop_last=False, num_workers=nw,
                      pin_memory=(device.type == "cuda"), persistent_workers=(nw > 0),
                      worker_init_fn=_worker_init_fn, generator=g)


def compute_class_weights(train_df: pd.DataFrame, n_classes: int) -> torch.Tensor:
    counts = np.bincount(train_df["label"].astype(int), minlength=n_classes).astype(np.float64)
    w = counts.sum() / (n_classes * np.maximum(counts, 1))
    return torch.tensor(w, dtype=torch.float32)

# CELL 8 — Model creation
def resolve_timm_name(model_name: str, cfg: dict = CONFIG) -> str:
    if model_name == "convnext_tiny":
        return "convnext_tiny"
    if model_name == "efficientnetv2_s":
        return "tf_efficientnetv2_s"   # NB: timm's default tf_ weights were trained with mean/std 0.5; we still use ImageNet stats (see warning)
    if model_name == "mobilenetv4":
        return cfg["MOBILENETV4_VARIANT"]
    raise ValueError(f"Unknown model_name '{model_name}'. Supported: convnext_tiny, efficientnetv2_s, mobilenetv4")


def create_model(model_name: str, num_classes: int, pretrained: bool = True, cfg: dict = CONFIG) -> nn.Module:
    """Create a timm model with a fresh classifier of size `num_classes`."""
    timm_name = resolve_timm_name(model_name, cfg)
    available = timm.list_models()
    if timm_name not in available:
        if model_name == "mobilenetv4":
            found = timm.list_models("*mobilenetv4*")
            msg = (f"MobileNetV4 variant '{timm_name}' not available in timm {timm.__version__}. "
                   f"MobileNetV4-like models found: {found or 'NONE'}. "
                   + ("Set CONFIG['MOBILENETV4_VARIANT'] to one of these." if found else
                      "Your timm is too old: run `pip install -U 'timm>=1.0.9'` and restart the runtime."))
            raise RuntimeError(msg)
        raise RuntimeError(f"timm model '{timm_name}' not found in timm {timm.__version__}.")
    try:
        model = timm.create_model(timm_name, pretrained=pretrained, num_classes=num_classes)
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(f"Failed to create '{timm_name}' (pretrained={pretrained}). If this is a download error, "
                           f"check internet access / HF hub availability. Original: {e}") from e
    out_features = model.get_classifier().out_features
    if out_features != num_classes:
        raise RuntimeError(f"Classifier replacement failed: {out_features} outputs, expected {num_classes}.")
    pc = getattr(model, "pretrained_cfg", {}) or {}
    if pretrained and pc.get("mean") is not None and not np.allclose(pc["mean"], IMAGENET_MEAN, atol=1e-3):
        print(f"  WARNING: {timm_name} pretrained weights expect mean={pc['mean']}, std={pc.get('std')}, "
              f"but the pipeline uses ImageNet stats {IMAGENET_MEAN}/{IMAGENET_STD} as specified. "
              f"Fine-tuning will adapt, but be aware of the mismatch.")
    model.meta = {"model_name": model_name, "timm_name": timm_name}
    return model


# quick availability report (does not download weights)
for _m in CONFIG["MODELS"]:
    _n = resolve_timm_name(_m)
    print(f"{_m:<18s} -> timm '{_n}' : {'available' if _n in timm.list_models() else 'NOT AVAILABLE'}")

# CELL 9 — Training utilities
class FocalLoss(nn.Module):
    """Multi-class focal loss with optional class weights."""

    def __init__(self, gamma: float = 2.0, weight: Optional[torch.Tensor] = None):
        super().__init__()
        self.gamma, self.weight = gamma, weight

    def forward(self, logits, target):
        logp = F.log_softmax(logits.float(), dim=1)
        ce = F.nll_loss(logp, target, weight=self.weight, reduction="none")
        pt = torch.exp(-F.nll_loss(logp, target, reduction="none"))
        return ((1 - pt) ** self.gamma * ce).mean()


def make_scaler(enabled: bool):
    try:
        return torch.amp.GradScaler("cuda", enabled=enabled)
    except (AttributeError, TypeError):
        return torch.cuda.amp.GradScaler(enabled=enabled)


def train_one_epoch(model, loader, criterion, optimizer, scaler, use_amp: bool) -> Tuple[float, float]:
    model.train()
    total_loss, correct, n = 0.0, 0, 0
    for x, y in tqdm(loader, desc="  train", leave=False):
        x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        with torch.autocast(device_type=device.type, enabled=use_amp):
            logits = model(x)
            loss = criterion(logits, y)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()
        total_loss += loss.item() * x.size(0)
        correct += (logits.argmax(1) == y).sum().item()
        n += x.size(0)
    return total_loss / n, correct / n


@torch.no_grad()
def predict_loader(model, loader, criterion=None, use_amp: bool = False):
    """Returns (loss|None, y_true, y_pred, probs[N,C])."""
    model.eval()
    ys, ps, probs, total_loss, n = [], [], [], 0.0, 0
    for x, y in tqdm(loader, desc="  eval ", leave=False):
        x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
        with torch.autocast(device_type=device.type, enabled=use_amp):
            logits = model(x)
        if criterion is not None:
            total_loss += criterion(logits.float(), y).item() * x.size(0)
        n += x.size(0)
        pr = torch.softmax(logits.float(), 1)
        probs.append(pr.cpu().numpy())
        ps.append(pr.argmax(1).cpu().numpy())
        ys.append(y.cpu().numpy())
    return (total_loss / n if criterion is not None else None), np.concatenate(ys), np.concatenate(ps), np.concatenate(probs)


def validate_one_epoch(model, loader, criterion, use_amp: bool) -> Dict[str, float]:
    loss, yt, yp, _ = predict_loader(model, loader, criterion, use_amp)
    _, _, f1, _ = precision_recall_fscore_support(yt, yp, average="macro", zero_division=0)
    return {"loss": loss, "acc": accuracy_score(yt, yp), "macro_f1": f1}


def save_checkpoint(path: Path, model, model_name: str, class_names: List[str], val_metric: float,
                    epoch: int, cfg: dict = CONFIG, extra: Optional[dict] = None) -> None:
    ckpt = {
        "model_name": model_name,
        "timm_name": resolve_timm_name(model_name, cfg),
        "class_names": list(class_names),
        "state_dict": {k: v.detach().cpu() for k, v in model.state_dict().items()},
        "image_size": cfg["IMAGE_SIZE"],
        "normalization": {"mean": IMAGENET_MEAN, "std": IMAGENET_STD},
        "config": json.loads(json.dumps(cfg, default=str)),
        "val_metric": {"name": "val_macro_f1", "value": float(val_metric)},
        "epoch": int(epoch),
        "timm_version": timm.__version__, "torch_version": torch.__version__,
    }
    if extra:
        ckpt.update(extra)
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(ckpt, path)


def load_checkpoint(path: Union[str, Path]) -> Tuple[nn.Module, dict]:
    """Rebuild the architecture from the checkpoint, load weights, attach `model.meta`, return (model, ckpt)."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {path}")
    try:
        ckpt = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        ckpt = torch.load(path, map_location="cpu")
    model = create_model(ckpt["model_name"], len(ckpt["class_names"]), pretrained=False)
    model.load_state_dict(ckpt["state_dict"])
    model.to(device).eval()
    model.meta = {"model_name": ckpt["model_name"], "timm_name": ckpt["timm_name"],
                  "class_names": ckpt["class_names"], "image_size": ckpt["image_size"],
                  "mean": ckpt["normalization"]["mean"], "std": ckpt["normalization"]["std"]}
    return model, ckpt


def train_model(model_name: str, train_df: pd.DataFrame, val_df: pd.DataFrame, class_names: List[str],
                ckpt_path: Path, tag: str, cfg: dict = CONFIG) -> dict:
    """Fine-tune one model; checkpoint on best validation macro-F1; early stopping; cosine LR schedule."""
    set_seed(cfg["SEED"], cfg["DETERMINISTIC"])
    print(f"\n{'=' * 70}\nTRAINING {tag} | train={len(train_df)} val={len(val_df)} | device={device}\n{'=' * 70}")
    model = create_model(model_name, len(class_names), cfg["PRETRAINED"], cfg).to(device)
    train_loader, val_loader = make_loader(train_df, True, cfg), make_loader(val_df, False, cfg)
    weights = compute_class_weights(train_df, len(class_names)).to(device) if cfg["USE_CLASS_WEIGHTS"] else None
    criterion = FocalLoss(cfg["FOCAL_GAMMA"], weights) if cfg["USE_FOCAL_LOSS"] else nn.CrossEntropyLoss(weight=weights)
    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg["LEARNING_RATE"], weight_decay=cfg["WEIGHT_DECAY"])
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=cfg["NUM_EPOCHS"], eta_min=cfg["LEARNING_RATE"] * 0.01)
    scaler = make_scaler(USE_AMP)

    hist, best_f1, best_epoch, bad_epochs = [], -1.0, 0, 0
    for epoch in range(1, cfg["NUM_EPOCHS"] + 1):
        t0 = time.time()
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer, scaler, USE_AMP)
        val = validate_one_epoch(model, val_loader, criterion, USE_AMP)
        lr = optimizer.param_groups[0]["lr"]
        scheduler.step()
        hist.append({"epoch": epoch, "train_loss": tr_loss, "train_acc": tr_acc, "val_loss": val["loss"],
                     "val_acc": val["acc"], "val_macro_f1": val["macro_f1"], "lr": lr})
        improved = val["macro_f1"] > best_f1
        if improved:
            best_f1, best_epoch, bad_epochs = val["macro_f1"], epoch, 0
            save_checkpoint(ckpt_path, model, model_name, class_names, best_f1, epoch, cfg)
        else:
            bad_epochs += 1
        print(f"[{tag}] ep {epoch:02d}/{cfg['NUM_EPOCHS']} | loss {tr_loss:.4f}/{val['loss']:.4f} | "
              f"acc {tr_acc:.4f}/{val['acc']:.4f} | val F1 {val['macro_f1']:.4f}{' *' if improved else ''} | {time.time() - t0:.0f}s")
        if bad_epochs >= cfg["EARLY_STOP_PATIENCE"]:
            print(f"Early stopping at epoch {epoch} (best epoch {best_epoch}, val macro-F1 {best_f1:.4f}).")
            break
    history = pd.DataFrame(hist)
    history.to_csv(DIRS["results"] / f"{tag}_history.csv", index=False)
    plot_training_history(history, tag)
    del model, optimizer
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return {"tag": tag, "ckpt_path": str(ckpt_path), "best_val_f1": best_f1, "best_epoch": best_epoch, "history": history}


def plot_training_history(history: pd.DataFrame, tag: str) -> Path:
    fig, ax = plt.subplots(1, 2, figsize=(12, 4))
    ax[0].plot(history.epoch, history.train_loss, label="train loss")
    ax[0].plot(history.epoch, history.val_loss, label="validation loss")
    ax[0].set(title=f"{tag} — loss", xlabel="epoch", ylabel="loss"); ax[0].legend(); ax[0].grid(alpha=.3)
    ax[1].plot(history.epoch, history.train_acc, label="train accuracy")
    ax[1].plot(history.epoch, history.val_acc, label="validation accuracy")
    ax[1].set(title=f"{tag} — accuracy", xlabel="epoch", ylabel="accuracy"); ax[1].legend(); ax[1].grid(alpha=.3)
    fig.tight_layout()
    path = DIRS["plots"] / f"{tag}_training_curves.png"
    fig.savefig(path, dpi=150); plt.show(); plt.close(fig)
    return path


def plot_confusion_matrix(cm: np.ndarray, class_names: List[str], title: str, path: Path) -> None:
    cmn = cm / np.maximum(cm.sum(1, keepdims=True), 1)
    fig, ax = plt.subplots(figsize=(0.9 * len(class_names) + 3, 0.8 * len(class_names) + 2.5))
    im = ax.imshow(cmn, cmap="Blues", vmin=0, vmax=1)
    ax.set_xticks(range(len(class_names))); ax.set_yticks(range(len(class_names)))
    ax.set_xticklabels(class_names, rotation=45, ha="right"); ax.set_yticklabels(class_names)
    for i in range(len(class_names)):
        for j in range(len(class_names)):
            ax.text(j, i, int(cm[i, j]), ha="center", va="center", color="white" if cmn[i, j] > .5 else "black", fontsize=8)
    ax.set(title=f"{title}\n(cell = count, colour = row-normalised)", xlabel="Predicted", ylabel="True")
    fig.colorbar(im, ax=ax, fraction=0.046); fig.tight_layout()
    fig.savefig(path, dpi=150); plt.show(); plt.close(fig)


def evaluate_model(ckpt_path: Union[str, Path], test_df: pd.DataFrame, tag: str, cfg: dict = CONFIG) -> dict:
    """Evaluate a checkpoint on the held-out test set; saves CSVs + confusion-matrix plot."""
    model, ckpt = load_checkpoint(ckpt_path)
    cn = ckpt["class_names"]
    _, yt, yp, _ = predict_loader(model, make_loader(test_df, False, cfg), None, USE_AMP)
    p, r, f1, _ = precision_recall_fscore_support(yt, yp, average="macro", zero_division=0)
    metrics = {"Model": tag, "Accuracy": accuracy_score(yt, yp), "Macro Precision": p, "Macro Recall": r, "Macro F1": f1,
               "N_test": len(yt)}
    labels = list(range(len(cn)))
    cm = confusion_matrix(yt, yp, labels=labels)
    report = pd.DataFrame(classification_report(yt, yp, labels=labels, target_names=cn, output_dict=True, zero_division=0)).T
    pd.DataFrame([metrics]).to_csv(DIRS["results"] / f"{tag}_test_metrics.csv", index=False)
    report.to_csv(DIRS["results"] / f"{tag}_classification_report.csv")
    pd.DataFrame(cm, index=cn, columns=cn).to_csv(DIRS["results"] / f"{tag}_confusion_matrix.csv")
    plot_confusion_matrix(cm, cn, f"{tag} — test confusion matrix", DIRS["plots"] / f"{tag}_confusion_matrix.png")
    print(f"\n--- {tag}: per-class report (test) ---\n{report.round(4).to_string()}")
    del model
    return {"metrics": metrics, "cm": cm, "report": report}


TRAINED: Dict[str, dict] = {}     # model_name -> {"runs": [...], "selected_ckpt": str}
EVAL: Dict[str, dict] = {}        # model_name -> {"selected": {...}, "runs": [...]}


def run_model_training(model_name: str, split_df: pd.DataFrame, class_names: List[str], cfg: dict = CONFIG) -> dict:
    """Single train/val run, or stratified group 5-fold CV over the train+val pool (test set stays untouched)."""
    ck_dir = DIRS["checkpoints"]
    train_df, val_df = split_df[split_df.split == "train"], split_df[split_df.split == "val"]
    if not cfg["USE_5_FOLD_CV"]:
        run = train_model(model_name, train_df, val_df, class_names, ck_dir / f"{model_name}_best.pth", model_name, cfg)
        return {"runs": [run], "selected_ckpt": run["ckpt_path"]}
    pool = split_df[split_df.split.isin(["train", "val"])].reset_index(drop=True)
    skf = StratifiedGroupKFold(n_splits=cfg["N_FOLDS"], shuffle=True, random_state=cfg["SEED"])
    runs = []
    for k, (tr, va) in enumerate(skf.split(pool, pool["label"], pool["group_id"]), start=1):
        runs.append(train_model(model_name, pool.iloc[tr], pool.iloc[va], class_names,
                                ck_dir / f"{model_name}_fold{k}_best.pth", f"{model_name}_fold{k}", cfg))
    best = max(runs, key=lambda r: r["best_val_f1"])          # selected by VALIDATION metric only
    shutil.copy(best["ckpt_path"], ck_dir / f"{model_name}_best.pth")
    print(f"CV: checkpoint of {best['tag']} (highest validation macro-F1) saved as {model_name}_best.pth")
    return {"runs": runs, "selected_ckpt": str(ck_dir / f"{model_name}_best.pth")}

# CELL 10 — Train ConvNeXt-Tiny
if "convnext_tiny" in CONFIG["MODELS"]:
    TRAINED["convnext_tiny"] = run_model_training("convnext_tiny", SPLIT_DF, class_names)

# CELL 11 — Train EfficientNetV2-S
if "efficientnetv2_s" in CONFIG["MODELS"]:
    TRAINED["efficientnetv2_s"] = run_model_training("efficientnetv2_s", SPLIT_DF, class_names)

# CELL 12 — Train MobileNetV4
if "mobilenetv4" in CONFIG["MODELS"]:
    TRAINED["mobilenetv4"] = run_model_training("mobilenetv4", SPLIT_DF, class_names)

# CELL 13 — Evaluate all models on the held-out test set
def evaluate_all(split_df: pd.DataFrame) -> Dict[str, dict]:
    test_df = split_df[split_df.split == "test"]
    if test_df.empty:
        raise RuntimeError("Test split is empty.")
    out = {}
    for name, info in TRAINED.items():
        res = {"runs": []}
        if CONFIG["USE_5_FOLD_CV"]:
            for run in info["runs"]:
                res["runs"].append(evaluate_model(run["ckpt_path"], test_df, run["tag"])["metrics"])
        res["selected"] = evaluate_model(info["selected_ckpt"], test_df, name)
        out[name] = res
    return out


EVAL = evaluate_all(SPLIT_DF)

# CELL 14 — Classification result comparison (objective report, no automatic ranking)
def comparison_tables() -> pd.DataFrame:
    order = [m for m in CONFIG["MODELS"] if m in EVAL]                   # config order, NOT sorted by score
    cols = ["Model", "Accuracy", "Macro Precision", "Macro Recall", "Macro F1"]
    table = pd.DataFrame([EVAL[m]["selected"]["metrics"] for m in order])[cols]
    table.to_csv(DIRS["results"] / "model_comparison.csv", index=False)
    print("Test-set comparison (checkpoint selected on validation macro-F1):\n")
    print(table.round(4).to_string(index=False))
    if CONFIG["USE_5_FOLD_CV"]:
        rows = []
        for m in order:
            df = pd.DataFrame(EVAL[m]["runs"])
            row = {"Model": m}
            for c in cols[1:]:
                row[c] = f"{df[c].mean():.4f} ± {df[c].std(ddof=1):.4f}"
            rows.append(row)
        cv = pd.DataFrame(rows)
        cv.to_csv(DIRS["results"] / "model_comparison_cv_mean_std.csv", index=False)
        print("\nCross-validation fold models on the held-out test set (mean ± std over folds):\n")
        print(cv.to_string(index=False))
    return table


COMPARISON = comparison_tables()

# CELL 15 — XAI target-layer detection
def _layer_name(model: nn.Module, layer: nn.Module) -> str:
    for n, m in model.named_modules():
        if m is layer:
            return n
    return layer.__class__.__name__


def validate_target_layer(model: nn.Module, layer: nn.Module, image_size: int) -> Tuple[int, ...]:
    """Dry-run forward pass to confirm the layer emits a 4-D spatial tensor (B,C,H,W) with H,W > 1."""
    cap: Dict[str, torch.Tensor] = {}
    h = layer.register_forward_hook(lambda m, i, o: cap.setdefault("o", o))
    was_training = model.training
    model.eval()
    try:
        dev = next(model.parameters()).device
        with torch.no_grad():
            model(torch.zeros(1, 3, image_size, image_size, device=dev))
    finally:
        h.remove()
        model.train(was_training)
    out = cap.get("o")
    if not isinstance(out, torch.Tensor) or out.ndim != 4 or min(out.shape[-2:]) <= 1:
        shape = tuple(out.shape) if isinstance(out, torch.Tensor) else type(out).__name__
        raise RuntimeError(f"Invalid CAM target layer '{_layer_name(model, layer)}': output {shape} is not a "
                           f"spatial (B,C,H,W) feature map.")
    return tuple(out.shape)


def get_target_layers(model: nn.Module, model_name: str, image_size: Optional[int] = None, verbose: bool = True) -> List[nn.Module]:
    """Model-specific final spatial feature layer for CAM methods (validated with a dry run).

    convnext_tiny    -> model.stages[-1]      (last ConvNeXt stage, 7x7 for 224 input)
    efficientnetv2_s -> model.blocks[-1][-1]  (last MBConv/FusedMBConv block before conv_head)
    mobilenetv4      -> model.blocks[-1]      (last feature stage before conv_head/pooling)
    """
    meta = getattr(model, "meta", {})
    image_size = image_size or meta.get("image_size", CONFIG["IMAGE_SIZE"])
    cached = meta.get("target_layers")
    if cached is not None:
        return cached
    try:
        if model_name == "convnext_tiny":
            layer = model.stages[-1]
        elif model_name == "efficientnetv2_s":
            layer = model.blocks[-1][-1]
        elif model_name == "mobilenetv4":
            layer = model.blocks[-1]
        else:
            raise ValueError(f"No target-layer rule for model '{model_name}'.")
    except (AttributeError, IndexError, TypeError) as e:
        raise RuntimeError(f"Could not locate target layer for '{model_name}' in timm model "
                           f"{model.__class__.__name__}: {e}") from e
    shape = validate_target_layer(model, layer, image_size)
    if verbose:
        print(f"[target layer] {model_name}: '{_layer_name(model, layer)}' -> {layer.__class__.__name__}, output shape {shape}")
    meta["target_layers"] = [layer]
    model.meta = meta
    return [layer]


for _name, _info in TRAINED.items():
    _m, _ = load_checkpoint(_info["selected_ckpt"])
    get_target_layers(_m, _name)
    del _m

# CELL 16 — Grad-CAM++ / Layer-CAM / Eigen-CAM implementation
try:
    from pytorch_grad_cam import GradCAMPlusPlus, LayerCAM, EigenCAM
    from pytorch_grad_cam.utils.image import show_cam_on_image
    from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
except ImportError as e:
    raise ImportError("pytorch-grad-cam missing. Install with `pip install grad-cam` (CELL 1).") from e

try:
    from importlib.metadata import version as _pkg_version
    GRADCAM_VERSION = _pkg_version("grad-cam")
except Exception:  # noqa: BLE001
    GRADCAM_VERSION = "unknown"
print(f"pytorch-grad-cam version: {GRADCAM_VERSION}")

CAM_REGISTRY = {"gradcam++": GradCAMPlusPlus, "layercam": LayerCAM, "eigencam": EigenCAM}
CAM_DISPLAY = {"gradcam++": "Grad-CAM++", "layercam": "Layer-CAM", "eigencam": "Eigen-CAM"}
CAM_FILENAME = {"gradcam++": "gradcampp", "layercam": "layercam", "eigencam": "eigencam"}


def load_rgb(image: Union[str, Path, Image.Image, np.ndarray]) -> np.ndarray:
    if isinstance(image, (str, Path)):
        if not Path(image).exists():
            raise FileNotFoundError(f"Image not found: {image}")
        return np.array(Image.open(image).convert("RGB"))
    if isinstance(image, Image.Image):
        return np.array(image.convert("RGB"))
    arr = np.asarray(image)
    if arr.ndim != 3 or arr.shape[2] != 3:
        raise ValueError(f"Expected HxWx3 RGB array, got {arr.shape}")
    return arr.astype(np.uint8)


def preprocess_image(image, image_size: int, mean: Sequence[float], std: Sequence[float]) -> Tuple[torch.Tensor, np.ndarray]:
    """Same deterministic preprocessing as validation/test. Returns (tensor[1,3,S,S], resized RGB float32 in [0,1])."""
    rgb = load_rgb(image)
    tf = A.Compose([A.Resize(height=image_size, width=image_size), A.Normalize(mean=mean, std=std), ToTensorV2()])
    tensor = tf(image=rgb)["image"].unsqueeze(0)
    resized = cv2.resize(rgb, (image_size, image_size), interpolation=cv2.INTER_LINEAR)
    return tensor, resized.astype(np.float32) / 255.0


@torch.no_grad()
def predict_tensor(model: nn.Module, tensor: torch.Tensor) -> Tuple[int, float, np.ndarray]:
    model.eval()
    probs = torch.softmax(model(tensor.to(device)).float(), 1)[0].cpu().numpy()
    idx = int(probs.argmax())
    return idx, float(probs[idx]), probs


def _resolve_target(target_class, class_names: List[str]) -> Optional[int]:
    if target_class is None:
        return None
    if isinstance(target_class, str):
        if target_class not in class_names:
            raise ValueError(f"Unknown target_class '{target_class}'. Known: {class_names}")
        return class_names.index(target_class)
    if not 0 <= int(target_class) < len(class_names):
        raise ValueError(f"target_class index {target_class} out of range [0,{len(class_names) - 1}]")
    return int(target_class)


def generate_xai(model: nn.Module, tensor: torch.Tensor, rgb_float: np.ndarray, method: str,
                 target_layers: List[nn.Module], target_idx: Optional[int] = None) -> Tuple[np.ndarray, np.ndarray]:
    """Run one CAM method. Returns (heatmap[H,W] in [0,1], overlay uint8 RGB).

    target_idx=None -> explain the model's predicted class. NOTE: Eigen-CAM is class-agnostic (first principal
    component of the activations) and ignores the target; Grad-CAM++/Layer-CAM explain the target class.
    """
    method = method.lower()
    if method not in CAM_REGISTRY:
        raise ValueError(f"Unsupported XAI method '{method}'. Supported: {list(CAM_REGISTRY)}")
    cls = CAM_REGISTRY[method]
    kwargs = {"model": model, "target_layers": target_layers}
    if "use_cuda" in inspect.signature(cls.__init__).parameters:      # older pytorch-grad-cam versions
        kwargs["use_cuda"] = device.type == "cuda"
    targets = [ClassifierOutputTarget(target_idx)] if target_idx is not None else None
    model.eval()
    cam = cls(**kwargs)
    try:
        with torch.enable_grad():
            gray = cam(input_tensor=tensor.to(device), targets=targets)[0]
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(f"pytorch-grad-cam {GRADCAM_VERSION} failed for '{method}' on layer "
                           f"'{_layer_name(model, target_layers[0])}': {e}") from e
    finally:
        ag = getattr(cam, "activations_and_grads", None)
        if ag is not None and hasattr(ag, "release"):
            ag.release()
    overlay = show_cam_on_image(rgb_float, gray, use_rgb=True)
    return gray, overlay


def generate_explanation(model: nn.Module, image, method: str, target_class=None,
                         model_name: Optional[str] = None) -> Tuple[np.ndarray, np.ndarray]:
    """Public interface: generate_explanation(model, image, method, target_class=None) -> (heatmap, overlay).
    `model` must come from load_checkpoint (carries model.meta with class names / normalization)."""
    meta = getattr(model, "meta", None)
    if not meta or "class_names" not in meta:
        raise ValueError("model.meta missing — load the model with load_checkpoint().")
    model_name = model_name or meta["model_name"]
    tensor, rgb = preprocess_image(image, meta["image_size"], meta["mean"], meta["std"])
    layers = get_target_layers(model, model_name, meta["image_size"], verbose=False)
    return generate_xai(model, tensor, rgb, method, layers, _resolve_target(target_class, meta["class_names"]))

# CELL 17 — Single-image XAI inference
_MODEL_CACHE: Dict[str, Tuple[nn.Module, dict]] = {}


def _get_model(model_name: str, checkpoint_path: Union[str, Path]) -> nn.Module:
    key = str(checkpoint_path)
    if key not in _MODEL_CACHE:
        model, ckpt = load_checkpoint(checkpoint_path)
        if ckpt["model_name"] != model_name:
            raise ValueError(f"Checkpoint holds '{ckpt['model_name']}' but model_name='{model_name}' was requested.")
        _MODEL_CACHE[key] = (model, ckpt)
    return _MODEL_CACHE[key][0]


def predict_image(image_path, model_name: str, checkpoint_path) -> Tuple[str, float, Dict[str, float]]:
    """Returns (predicted_class, confidence, {class_name: probability})."""
    model = _get_model(model_name, checkpoint_path)
    m = model.meta
    tensor, _ = preprocess_image(image_path, m["image_size"], m["mean"], m["std"])
    idx, conf, probs = predict_tensor(model, tensor)
    return m["class_names"][idx], conf, {c: float(p) for c, p in zip(m["class_names"], probs)}


def _save_rgb(arr: np.ndarray, path: Path) -> None:
    if arr.dtype != np.uint8:
        arr = (np.clip(arr, 0, 1) * 255).astype(np.uint8)
    Image.fromarray(arr).save(path)


def explain_loaded(model: nn.Module, image_path, methods: Sequence[str], out_dir: Path,
                   true_label: Optional[str] = None) -> dict:
    """Predict + explain with an already-loaded model; save original/method/comparison images."""
    out_dir.mkdir(parents=True, exist_ok=True)
    m = model.meta
    tensor, rgb = preprocess_image(image_path, m["image_size"], m["mean"], m["std"])
    idx, conf, _ = predict_tensor(model, tensor)
    pred = m["class_names"][idx]
    layers = get_target_layers(model, m["model_name"], m["image_size"], verbose=False)
    _save_rgb(rgb, out_dir / "original.png")
    overlays = {}
    for meth in methods:
        _, ov = generate_xai(model, tensor, rgb, meth, layers, None)          # explains the predicted class
        overlays[meth] = ov
        _save_rgb(ov, out_dir / f"{CAM_FILENAME[meth]}.png")
    n = 1 + len(overlays)
    fig, axes = plt.subplots(1, n, figsize=(4.2 * n, 4.9))
    axes = np.atleast_1d(axes)
    axes[0].imshow(rgb); axes[0].set_title("Original" + (f"\ntrue: {true_label}" if true_label else ""), fontsize=10)
    for ax, meth in zip(axes[1:], overlays):
        ax.imshow(overlays[meth]); ax.set_title(CAM_DISPLAY[meth], fontsize=10)
    for ax in axes:
        ax.axis("off")
    fig.suptitle(f"Model: {m['model_name']} | Predicted: {pred} | Confidence: {conf:.2%}\n"
                 f"Visual explanations only — no quantitative faithfulness/localisation evaluation", fontsize=11)
    fig.tight_layout()
    fig.savefig(out_dir / "comparison.png", dpi=150, bbox_inches="tight")
    plt.show(); plt.close(fig)
    return {"image": str(image_path), "true_label": true_label, "pred": pred, "confidence": conf,
            "correct": (true_label == pred) if true_label else None, "out_dir": str(out_dir)}


def explain_image(image_path, model_name: str, checkpoint_path, methods: Sequence[str] = ("gradcam++", "layercam", "eigencam"),
                  out_dir: Optional[Union[str, Path]] = None, true_label: Optional[str] = None) -> dict:
    """Load checkpoint, predict, and save Grad-CAM++/Layer-CAM/Eigen-CAM explanations for one image."""
    model = _get_model(model_name, checkpoint_path)
    print(f"[target layer] {model_name}: '{_layer_name(model, get_target_layers(model, model_name, verbose=False)[0])}'")
    out_dir = Path(out_dir) if out_dir else DIRS["xai"] / model_name / Path(str(image_path)).stem
    return explain_loaded(model, image_path, methods, out_dir, true_label)


if TRAINED:
    _test_df = SPLIT_DF[SPLIT_DF.split == "test"]
    _demo = CONFIG["DEMO_IMAGE_PATH"] or _test_df.iloc[0]["path"]
    _true = _test_df.loc[_test_df.path == _demo, "class_name"].squeeze() if (_test_df.path == _demo).any() else None
    for _name, _info in TRAINED.items():
        print(predict_image(_demo, _name, _info["selected_ckpt"])[:2])
        explain_image(_demo, _name, _info["selected_ckpt"], CONFIG["XAI_METHODS"],
                      out_dir=DIRS["xai"] / _name / "demo", true_label=_true if isinstance(_true, str) else None)

# CELL 18 — Batch XAI visualization
def run_xai_batch(model_name: str, checkpoint_path, test_df: pd.DataFrame, n: int, seed: int,
                  methods: Sequence[str] = ("gradcam++", "layercam", "eigencam")) -> pd.DataFrame:
    """Explain N randomly chosen test images (fixed seed) with one model; writes xai/<model>/image_XXX/."""
    model = _get_model(model_name, checkpoint_path)
    layer = get_target_layers(model, model_name, verbose=False)[0]
    print(f"[target layer] {model_name}: '{_layer_name(model, layer)}'")
    test_df = test_df.reset_index(drop=True)
    idxs = random.Random(seed).sample(range(len(test_df)), min(n, len(test_df)))
    rows = []
    for k, i in enumerate(tqdm(idxs, desc=f"XAI {model_name}"), start=1):
        r = test_df.iloc[i]
        info = explain_loaded(model, r["path"], methods, DIRS["xai"] / model_name / f"image_{k:03d}", r["class_name"])
        rows.append(info)
    manifest = pd.DataFrame(rows)
    manifest.to_csv(DIRS["xai"] / model_name / "xai_manifest.csv", index=False)
    return manifest


XAI_MANIFESTS: Dict[str, pd.DataFrame] = {}
for _name, _info in TRAINED.items():
    XAI_MANIFESTS[_name] = run_xai_batch(_name, _info["selected_ckpt"], SPLIT_DF[SPLIT_DF.split == "test"],
                                         CONFIG["NUM_XAI_SAMPLES"], CONFIG["SEED"], CONFIG["XAI_METHODS"])

# CELL 19 — Save final experiment results
def save_final_results() -> Path:
    env = {"torch": torch.__version__, "timm": timm.__version__, "grad-cam": GRADCAM_VERSION,
           "albumentations": A.__version__, "numpy": np.__version__, "device": str(device),
           "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None, "amp": USE_AMP}
    payload = {"config": json.loads(json.dumps(CONFIG, default=str)), "environment": env,
               "class_names": class_names, "num_classes": num_classes,
               "n_corrupted_images": len(CORRUPTED),
               "test_metrics": {m: EVAL[m]["selected"]["metrics"] for m in EVAL},
               "selected_checkpoints": {m: TRAINED[m]["selected_ckpt"] for m in TRAINED},
               "best_val_macro_f1": {m: [r["best_val_f1"] for r in TRAINED[m]["runs"]] for m in TRAINED},
               "note": "XAI outputs are visual explanations only; no quantitative faithfulness or lesion-localisation "
                       "evaluation (Objectives 3/4) was performed."}
    path = DIRS["results"] / "experiment_summary.json"
    json.dump(payload, open(path, "w"), indent=2, default=float)
    return path


print("Saved:", save_final_results())

# CELL 20 — Final summary
def final_summary() -> None:
    print("=" * 70 + "\nFINAL SUMMARY\n" + "=" * 70)
    print(f"Classes ({num_classes}): {class_names}")
    print(f"Images: {len(SPLIT_DF)} | train {int((SPLIT_DF.split=='train').sum())} | "
          f"val {int((SPLIT_DF.split=='val').sum())} | test {int((SPLIT_DF.split=='test').sum())}")
    print("\nTest-set results (measured, unranked):")
    print(COMPARISON.round(4).to_string(index=False))
    print(f"\nCheckpoints : {DIRS['checkpoints']}\nPlots       : {DIRS['plots']}\n"
          f"CSV/JSON    : {DIRS['results']}\nXAI figures : {DIRS['xai']}")
    print("\nInterpretation limits: heatmaps are visual explanations only. Without quantitative evaluation against "
          "lesion ground truth (Objectives 3/4, not implemented), they must not be cited as evidence that a model "
          "attends to lesions rather than background, nor as causal explanations.")


final_summary()


def main() -> None:
    """Run the whole pipeline end-to-end (equivalent to running CELLS 4-20 in order)."""
    global DISCOVERED_DF, VALID_DF, CORRUPTED, class_names, class_to_idx, num_classes, SPLIT_DF, COMPARISON, EVAL
    set_seed(CONFIG["SEED"], CONFIG["DETERMINISTIC"])
    root = extract_dataset(CONFIG["ZIP_PATH"], DIRS["extracted"])
    DISCOVERED_DF = discover_dataset(root)
    VALID_DF, CORRUPTED = validate_images(DISCOVERED_DF)
    class_names = sorted(VALID_DF["class_name"].unique())
    class_to_idx = {c: i for i, c in enumerate(class_names)}
    num_classes = len(class_names)
    VALID_DF["label"] = VALID_DF["class_name"].map(class_to_idx)
    SPLIT_DF = create_splits(VALID_DF, CONFIG["VAL_FRAC"], CONFIG["TEST_FRAC"], CONFIG["SEED"], CONFIG["GROUP_BY_FILENAME"])
    for m in CONFIG["MODELS"]:
        TRAINED[m] = run_model_training(m, SPLIT_DF, class_names)
    EVAL = evaluate_all(SPLIT_DF)
    COMPARISON = comparison_tables()
    for m, info in TRAINED.items():
        XAI_MANIFESTS[m] = run_xai_batch(m, info["selected_ckpt"], SPLIT_DF[SPLIT_DF.split == "test"],
                                         CONFIG["NUM_XAI_SAMPLES"], CONFIG["SEED"], CONFIG["XAI_METHODS"])
    save_final_results()
    final_summary()

# Create dummy objects to test saving
epoch = 1
loss = 0.5
model = torch.nn.Linear(10, 2)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Save checkpoint
checkpoint = {
    "epoch": epoch,
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict(),
    "loss": loss,
}
torch.save(checkpoint, "checkpoint.pt")